<?php

declare(strict_types=1);


namespace WEBcoast\DotForms\DataHandling;


use TYPO3\CMS\Backend\Utility\BackendUtility;
use TYPO3\CMS\Core\Schema\TcaSchemaFactory;
use TYPO3\CMS\Core\Utility\ArrayUtility;
use TYPO3\CMS\Core\Utility\Exception\MissingArrayPathException;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class DataHandler extends \TYPO3\CMS\Core\DataHandling\DataHandler
{
    public function compareFieldArrayWithCurrentAndUnset($table, $id, $fieldArray): array
    {
        $incomingFieldArray = $fieldArray;
        $fieldArray = array_filter($fieldArray, function ($value) {
            return !str_contains($value, '.');
        }, ARRAY_FILTER_USE_KEY);
        $fieldArray = parent::compareFieldArrayWithCurrentAndUnset($table, $id, $fieldArray);

        // Compare dot fields with original records and add changes to history
        $currentRecord = BackendUtility::getRecord($table, $id);
        foreach ($incomingFieldArray as $fieldName => $fieldValue) {
            if (str_contains($fieldName, '.')) {
                $mainFieldName = substr($fieldName, 0, strpos($fieldName, '.'));
                $fieldParts = explode('.', substr($fieldName, strpos($fieldName, '.') + 1));
                $currentValue = json_decode($currentRecord[$mainFieldName] ?? '[]', true);
                foreach ($fieldParts as $fieldPart) {
                    if (!is_array($currentValue)) {
                        $currentValue = [];
                    }
                    $currentValue = $currentValue[$fieldPart] ?? null;
                }
                if ($currentValue !== $fieldValue) {
                    $this->historyRecords[$table . ':' . $id]['oldRecord'][$fieldName] = $currentValue;
                    $this->historyRecords[$table . ':' . $id]['newRecord'][$fieldName] = $fieldValue;
                    $fieldArray[$fieldName] = $fieldValue;
                }
            }
        }

        return $fieldArray;
    }

    public function fixUniqueInPid(string $table, $uidOrRow): void
    {
        if (!is_array($uidOrRow) && $uidOrRow !== null) {
            $uidOrRow = BackendUtility::getRecord($table, $uidOrRow, useDeleteClause: false);
        }
        if (is_array($uidOrRow)) {
            $schemaFactory = GeneralUtility::makeInstance(TcaSchemaFactory::class);
            $schema = $schemaFactory->get($table);

            foreach ($schema->getFields() as $field) {
                if (str_contains($field->getName(), '.')) {
                    $mainFieldName = substr($field->getName(), 0, strpos($field->getName(), '.'));
                    $data = json_decode($uidOrRow[$mainFieldName] ?? '[]', true);

                    try {
                        $uidOrRow[$field->getName()] = ArrayUtility::getValueByPath($data, substr($field->getName(), strpos($field->getName(), '.') + 1), '.');
                    } catch (MissingArrayPathException $e) {
                        $uidOrRow[$field->getName()] = null;
                    }
                }
            }
        }

        parent::fixUniqueInPid($table, $uidOrRow);
    }

    protected function fixUniqueInSite(string $table, array|int $uidOrRow): bool
    {
        if (!is_array($uidOrRow) && $uidOrRow !== null) {
            $uidOrRow = BackendUtility::getRecord($table, $uidOrRow, useDeleteClause: false);
        }
        if (is_array($uidOrRow)) {
            $schemaFactory = GeneralUtility::makeInstance(TcaSchemaFactory::class);
            $schema = $schemaFactory->get($table);

            foreach ($schema->getFields() as $field) {
                if (str_contains($field->getName(), '.')) {
                    $mainFieldName = substr($field->getName(), 0, strpos($field->getName(), '.'));
                    $data = json_decode($uidOrRow[$mainFieldName] ?? '[]', true);

                    try {
                        $uidOrRow[$field->getName()] = ArrayUtility::getValueByPath($data, substr($field->getName(), strpos($field->getName(), '.') + 1), '.');
                    } catch (MissingArrayPathException $e) {
                        $uidOrRow[$field->getName()] = null;
                    }
                }
            }
        }

        return parent::fixUniqueInSite($table, $uidOrRow); // TODO: Change the autogenerated stub
    }

    public function updateDB($table, $uid, $fieldArray, int $recordPid = 0): void
    {
        $fieldArray = $this->processDotFields($table, $uid, $fieldArray, 'update');

        parent::updateDB($table, $uid, $fieldArray, $recordPid);
    }

    public function insertDB($table, $id, $fieldArray, $_ = false, $suggestedUid = 0): ?int
    {
        $fieldArray = $this->processDotFields($table, $id, $fieldArray, 'new');

        return parent::insertDB($table, $id, $fieldArray, $_, $suggestedUid);
    }

    protected function processDotFields($table, $id, $fieldArray, $status): array
    {
        if ($status !== 'new') {
            $currentRecord = BackendUtility::getRecord($table, $id);
        } else {
            $currentRecord = [];
        }

        $dotFields = [];

        foreach ($fieldArray as $fieldName => $fieldValue) {
            if (str_contains($fieldName, '.')) {
                $mainFieldName = substr($fieldName, 0, strpos($fieldName, '.'));
                if (!isset($dotFields[$mainFieldName])) {
                    $dotFields[$mainFieldName] = json_decode($currentRecord[$mainFieldName] ?? '[]', true);
                }
                // Convert dot notation to array
                $fieldParts = explode('.', substr($fieldName, strpos($fieldName, '.') + 1));
                $currentArray = &$dotFields[$mainFieldName];
                foreach ($fieldParts as $fieldPart) {
                    if (!is_array($currentArray)) {
                        $currentArray = [];
                    }
                    $currentArray = &$currentArray[$fieldPart];
                }
                $currentArray = $fieldValue;
                unset($fieldArray[$fieldName]);
            }
        }

        foreach ($dotFields as $fieldName => $fieldValue) {
            $fieldArray[$fieldName] = json_encode($fieldValue);
        }

        return $fieldArray;
    }

}
